In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder,OrdinalEncoder
import pickle

In [3]:
df = pd.read_csv("Churn_Modelling.csv")
df

      RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
0             1    15634602   Hargrave  ...               1       101348.88      1
1             2    15647311       Hill  ...               1       112542.58      0
2             3    15619304       Onio  ...               0       113931.57      1
3             4    15701354       Boni  ...               0        93826.63      0
4             5    15737888   Mitchell  ...               1        79084.10      0
...         ...         ...        ...  ...             ...             ...    ...
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...               0        38190.78      0

[10000 rows x 14 columns]

In [13]:
df = df.drop(['RowNumber','CustomerId','Surname'],axis=1)

KeyError: "['RowNumber', 'CustomerId', 'Surname'] not found in axis"

In [14]:
df

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France  Female  ...               1        101348.88       1
1             608     Spain  Female  ...               1        112542.58       0
2             502    France  Female  ...               0        113931.57       1
3             699    France  Female  ...               0         93826.63       0
4             850     Spain  Female  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France    Male  ...               0         96270.64       0
9996          516    France    Male  ...               1        101699.77       0
9997          709    France  Female  ...               1         42085.58       1
9998          772   Germany    Male  ...               0         92888.52       1
9999          792    France  Female  ...               0         38190.78       0

[10000 rows x 11 columns]

In [17]:
label_encoder_gender = LabelEncoder()
df['Gender'] = label_encoder_gender.fit_transform(df['Gender'])
df

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France       0  ...               1        101348.88       1
1             608     Spain       0  ...               1        112542.58       0
2             502    France       0  ...               0        113931.57       1
3             699    France       0  ...               0         93826.63       0
4             850     Spain       0  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France       1  ...               0         96270.64       0
9996          516    France       1  ...               1        101699.77       0
9997          709    France       0  ...               1         42085.58       1
9998          772   Germany       1  ...               0         92888.52       1
9999          792    France       0  ...               0         38190.78       0

[10000 rows x 11 columns]

In [19]:
onehot_encode_geography = OneHotEncoder()
geo_encode = onehot_encode_geography.fit_transform(df[['Geography']])
geo_encode

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [21]:
onehot_encode_geography.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [24]:
print(geo_encode.toarray())

[[1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 ...
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]

In [26]:
geo_encode_df = pd.DataFrame(geo_encode.toarray(),columns=onehot_encode_geography.get_feature_names_out(['Geography']))
geo_encode_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [45]:
df=df.drop(columns=onehot_encode_geography.get_feature_names_out(['Geography']))
df

KeyError: "['Geography_France', 'Geography_Germany', 'Geography_Spain'] not found in axis"

In [46]:
df = pd.concat([df,geo_encode_df],axis=1)
df

      CreditScore Geography  ...  Geography_Germany  Geography_Spain
0             619    France  ...                0.0              0.0
1             608     Spain  ...                0.0              1.0
2             502    France  ...                0.0              0.0
3             699    France  ...                0.0              0.0
4             850     Spain  ...                0.0              1.0
...           ...       ...  ...                ...              ...
9995          771    France  ...                0.0              0.0
9996          516    France  ...                0.0              0.0
9997          709    France  ...                0.0              0.0
9998          772   Germany  ...                1.0              0.0
9999          792    France  ...                0.0              0.0

[10000 rows x 14 columns]

In [ ]:
df = df.drop(columns=['Geography'])

In [53]:
with open ('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)
    
with open ('onehot_encode_geography.pkl','wb') as file:
    pickle.dump(onehot_encode_geography,file)

In [54]:
df.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [55]:
## Exited is independent feature 
X= df.drop('Exited',axis=1)
Y = df['Exited']

In [56]:
X_train , X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [57]:
Scaler = StandardScaler()
X_train = Scaler.fit_transform(X_train)
X_test = Scaler.transform(X_test)

In [59]:
with open('Scaler.pkl','wb') as file:
    pickle.dump(Scaler,file)